camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://127.0.0.1:26500
      rest-address: http://127.0.0.1:8080

spring:
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-tripDb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  mail:
    host: smtp.ethereal.email
    port: 587
    username: destin.leffler31@ethereal.email
    password: 9gCwWpDR1aM3peN2Vd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
